### PR TITLE
Fix for work oder design admin page change1 and center seed change

### PR DESCRIPTION
**Pull request by chethandb**
Fix for work oder design admin page change1 and center seed change

### CODE REVIEW

**Review by chethandb — COMMENTED** [review]
Approve this

**Review by chethandb — COMMENTED** [review]
Approve this as well

**Review by chethandb — COMMENTED** [review]
And these two file changes

**Comment by chethandb** [comment]
If it's not allowing to accept individual commits do not accept the entire pull request.. just leave it as is..

**Comment by chethandb** [comment]
Could you please approve this pull request. All issues had been addressed and approved from other related developers

**Review by gvijayarangan — APPROVED** [review]

**Pull request merged**
